# Generated by Django 4.2.7 on 2025-09-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Query History', 'verbose_name_plural': 'Query Histories'},
        ),
        migrations.RemoveField(
            model_name='queryhistory',
            name='database_connection',
        ),
        migrations.RemoveField(
            model_name='queryhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='DatabaseConnection',
        ),
    ]
